package org.gooseapple.game.ui.background;

public enum RailroadType {
    RAILROAD, RAILROAD_WIRE_START, RAILROAD_WIRE_MIDDLE, RAILROAD_WIRE_END, RAILROAD_TOWN_1, RAILROAD_TOWN_2, RAILROAD_TRAIN_STATION
}
